# Generated by Django 2.2 on 2019-10-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20191003_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultural',
            name='event_quote_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informal',
            name='event_quote_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='event_quote_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
