# Generated by Django 2.2 on 2019-10-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20191003_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural',
            name='event_fees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informal',
            name='event_fees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technical',
            name='event_fees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
