# Generated by Django 2.2 on 2019-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20191003_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural',
            name='event_brief_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informal',
            name='event_brief_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technical',
            name='event_brief_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
