# Generated by Django 2.2 on 2020-02-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20191004_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural',
            name='url',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='informal',
            name='url',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='technical',
            name='url',
            field=models.URLField(blank=True, max_length=30),
        ),
    ]
