# Generated by Django 2.2 on 2019-10-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
