# Generated by Django 2.2.6 on 2020-01-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191004_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
