# Generated by Django 2.2 on 2020-01-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField()),
                ('blog_content', models.TextField()),
                ('blog_image', models.ImageField(upload_to='blogs_image')),
                ('author_name', models.TextField()),
                ('author_profile_link', models.URLField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
